name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10-dev']

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv sync --dev
    - name: Paint it black and check for dirt under the carpets
      run: |
        pipenv run lint
    - name: Install python_project_template package
      run: |
        pipenv run flit install --pth-file
    - name: Run tests
      run: |
        pipenv run test
    - name: Upload coverage to Codecov
      if: matrix.python-version == 3.7
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
